name: Clear All Caches

on:
  workflow_dispatch:

permissions:
  actions: write

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  clear-caches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          REPO: ${{ github.repository }}
        run: |
          gh api "repos/$REPO/actions/caches" --jq '.actions_caches[].id' | while read cache_id; do
            echo "Deleting cache id $cache_id"
            gh api --method DELETE /repos/$REPO/actions/caches/$cache_id
            sleep 1
          done
