name: Clear All Caches

on:
  workflow_dispatch:
    inputs:
      ccache:
        type: boolean
        default: false
      sccache:
        type: boolean
        default: false
      workspace:
        type: boolean
        default: false
      cpm:
        type: boolean
        default: false
      all:
        type: boolean
        default: false

permissions:
  actions: write

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  clear-caches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set default repo and login
        run: |
          gh repo set-default "${{ github.repository }}"
          echo -e "${{ github.token }}" | gh auth login --with-token
  
      - name: Delete all caches
        if: inputs.all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          gh cache delete --succeed-on-no-caches --all

      - name: Delete all workspace caches
        if: (!inputs.all) && inputs.workspace
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches \
            --paginate \
            -q '.actions_caches[] | select(.key | startswith("workspace-")) | .id' | sort -r |
          while read cache_id; do
            echo "Deleting cache id $cache_id"
            gh cache delete $cache_id
          done

      - name: Delete all ccache caches
        if: (!inputs.all) && inputs.ccache
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches \
            --paginate \
            -q '.actions_caches[] | select(.key | startswith("ccache-")) | .id' | sort -r |
          while read cache_id; do
            echo "Deleting cache id $cache_id"
            gh cache delete $cache_id
          done

      - name: Delete all sccache caches
        if: (!inputs.all) && inputs.sccache
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches \
            --paginate \
            -q '.actions_caches[] | select(.key | startswith("sccache-")) | .id' | sort -r |
          while read cache_id; do
            echo "Deleting cache id $cache_id"
            gh cache delete $cache_id
          done

      - name: Delete all cpm caches
        if: (!inputs.all) && inputs.cpm
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/caches \
            --paginate \
            -q '.actions_caches[] | select(.key | startswith("cpm-")) | .id' | sort -r |
          while read cache_id; do
            echo "Deleting cache id $cache_id"
            gh cache delete $cache_id
          done
